name = "clubhouse"
compatibility_date = "2024-01-01"
pages_build_output_dir = "dist"

[[d1_databases]]
binding = "DB"
database_name = "asgard-brain"
database_id = "b6275cb4-9c0f-4649-ae6a-f1c2e70e940f"
